# Site settings
name: Conquer the time
email: waynetomas@outlook.com
author: Wayne Tomas
#url: http://www.hifreud.com
resume_site: http://www.hifreud.com/Resume.io/
github: https://github.com/HADESAngelia/
baseurl: ""
description: Follow interest in CG&CV&HCI.
meta_description: 个人博客;政治着眼于当下，方程寓意于永恒。
motto: To the life to time,rather than to the time in life.
banner: 给时光以生命，而不是给生命以时光。

#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: HADESAngelia
highlighter: Pygments

# Build settings
markdown: kramdown

baidu_analysis: 94be4b0f9fc5d94cc0d0415ea6761ae9

#FB:
  #comments :
   # provider : duoshuo
    #duoshuo:
        #short_name : luoyan35714
    #disqus :
        #short_name : freudkang
    # facebook :
    #   appid : 123
    #   num_posts: 5
    #   width: 580
    #   colorscheme: light